### ISSUE TITLE
User Stories: Viewing Review Posts

### ISSUE THREAD

**Issue by Yazhmd** [Yazhmd/PlayPoint-Django-blog-Project-#4]
As a user I can view anyone blog post even if I am not registered,

Acceptance Criteria:

- [ ] User can view a blog/review post even if registered or unregistered
- [ ] User can access login page if they are an unregistered user to sign up and add a comment or create a new blog.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Created a Blog model in models.py, updated views.py to include a view for displaying blog posts, and modified URLs to include the new view.

You can review changes in this commit: https://github.com/mnmnk43434/Yazhmd-PlayPoint-Django-blog-Project--4/commit/97868407704d35134c36cdd4b626e2a2469f8e06.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
